//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public long ProductId { get; set; }
        public long CategoryId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ProductInfo ProductInfo1 { get; set; }
        public virtual ProductInfo ProductInfo2 { get; set; }
    }
}
