//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderMaster
    {
        public long OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string InvoiceNo { get; set; }
        public string CompanyName { get; set; }
        public long PAN_VAT_No { get; set; }
        public decimal Discount { get; set; }
        public decimal GrandTotal { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
